[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ed25519-dalek = { version = "2.1.1", features = ["serde"] }
sha2 = "0.10.2"
bincode = "1.3.3" 